version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://root:5123123@db:5432/shop?schema=public
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 5123123
      POSTGRES_DB: shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d shop"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: